-- This script modifies the database schema to support 5-digit Game IDs (Text) instead of strict UUIDs.
-- Run this in your Supabase SQL Editor.

BEGIN;

-- 1. Drop existing Foreign Key constraints that link to the games table
-- We use IF EXISTS to avoid errors if the constraint names are different, 
-- but these are the standard names generated by Supabase.
ALTER TABLE players DROP CONSTRAINT IF EXISTS players_game_id_fkey;
ALTER TABLE rolls DROP CONSTRAINT IF EXISTS rolls_game_id_fkey;

-- 2. Change the column types from UUID to TEXT
-- This allows both UUIDs (existing games) and new 5-digit IDs.
ALTER TABLE games ALTER COLUMN id TYPE text;
ALTER TABLE players ALTER COLUMN game_id TYPE text;
ALTER TABLE rolls ALTER COLUMN game_id TYPE text;

-- 3. Re-create the Foreign Key constraints
ALTER TABLE players 
    ADD CONSTRAINT players_game_id_fkey 
    FOREIGN KEY (game_id) 
    REFERENCES games(id)
    ON DELETE CASCADE; -- Optional: deletes players when game is deleted

ALTER TABLE rolls 
    ADD CONSTRAINT rolls_game_id_fkey 
    FOREIGN KEY (game_id) 
    REFERENCES games(id)
    ON DELETE CASCADE;

COMMIT;
